# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_videos_confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadVideosConfirmDialog(object):
    def setupUi(self, DownloadVideosConfirmDialog):
        DownloadVideosConfirmDialog.setObjectName("DownloadVideosConfirmDialog")
        DownloadVideosConfirmDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DownloadVideosConfirmDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(DownloadVideosConfirmDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DownloadVideosConfirmDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DownloadVideosConfirmDialog)
        self.buttonBox.accepted.connect(DownloadVideosConfirmDialog.accept)
        self.buttonBox.rejected.connect(DownloadVideosConfirmDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DownloadVideosConfirmDialog)

    def retranslateUi(self, DownloadVideosConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        DownloadVideosConfirmDialog.setWindowTitle(_translate("DownloadVideosConfirmDialog", "Download Videos Confirm"))
