# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'account_list_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountListWidget(object):
    def setupUi(self, AccountListWidget):
        AccountListWidget.setObjectName("AccountListWidget")
        AccountListWidget.resize(300, 445)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AccountListWidget.sizePolicy().hasHeightForWidth())
        AccountListWidget.setSizePolicy(sizePolicy)
        AccountListWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountListWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(AccountListWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addAccountButton = QtWidgets.QPushButton(self.groupBox)
        self.addAccountButton.setObjectName("addAccountButton")
        self.horizontalLayout.addWidget(self.addAccountButton)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.listView = QtWidgets.QListView(AccountListWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(AccountListWidget)
        QtCore.QMetaObject.connectSlotsByName(AccountListWidget)

    def retranslateUi(self, AccountListWidget):
        _translate = QtCore.QCoreApplication.translate
        AccountListWidget.setWindowTitle(_translate("AccountListWidget", "Form"))
        self.groupBox.setTitle(_translate("AccountListWidget", "Account"))
        self.addAccountButton.setText(_translate("AccountListWidget", "+"))
