# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_table_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoTableWidget(object):
    def setupUi(self, VideoTableWidget):
        VideoTableWidget.setObjectName("VideoTableWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoTableWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(VideoTableWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(VideoTableWidget)
        QtCore.QMetaObject.connectSlotsByName(VideoTableWidget)

    def retranslateUi(self, VideoTableWidget):
        _translate = QtCore.QCoreApplication.translate
        VideoTableWidget.setWindowTitle(_translate("VideoTableWidget", "Form"))
