# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_category_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoCategoryWidget(object):
    def setupUi(self, VideoCategoryWidget):
        VideoCategoryWidget.setObjectName("VideoCategoryWidget")
        VideoCategoryWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoCategoryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(VideoCategoryWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(VideoCategoryWidget)
        QtCore.QMetaObject.connectSlotsByName(VideoCategoryWidget)

    def retranslateUi(self, VideoCategoryWidget):
        _translate = QtCore.QCoreApplication.translate
        VideoCategoryWidget.setWindowTitle(_translate("VideoCategoryWidget", "Form"))
